export const ramenDataFull = [
    {
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQDfKkmf2J0C20_1dGr10gC2l20K8B8d64f_g&usqp=CAU',
      alt: 'Ramen',
      name: 'Shoyu Ramen',
      desc: 'Chicken Broth, Ramen Noodles, Soy sauce, Shashu pork, Togarashi, Fish cakes, Seafood, Corn, Bamboo shoots, Garlic, ajitsuke tamago (ramen egg), Bean sprouts, Mushrooms, Kimchi, Yuzukosho, Raw shredded cabbage',
      price: '15.99',
      button: 'Order Now',
    },
    {
      img: 'https://gastroplant.com/wp-content/uploads/2019/08/1406_Vegan-Shio-Ramen_550.jpg',
      alt: 'Ramen',
      name: 'Shio Ramen',
      desc: ' Cabbage, Broth(a mix of Sesame oil, Ginger, Garlic, Scallion, Dashi powder, Mirin, Sake, Sea salt, and water), Ramen Noodles, Char siu, Kakuni, Ramen egg, Beans sprouts, Kikurage, Raw shredded cabbage, Kamaboko, Shichimi togarashi',
      price: '17.99',
      button: 'Add to Cart',
    },
    {
      img: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/miso-ramen-514e2ca.jpg?quality=90&webp=true&resize=440,400',
      alt: 'Ramen',
      name: 'Miso Ramen',
      desc: ' Chicken broth, Chili Bean Sauce/Paste, Sesame Seeds and Sesame Oil, White pepper powder, Miso, Ramen Noodles, Corn, Bamboo shoots, Garlic, ajitsuke tamago (ramen egg),  Bean sprouts, Mushrooms, Raw shredded cabbage ',
      price: '19.99',
      button: 'Order Now',
    },
    {
      img: 'https://cloudfront.chushikokuandtokyo.org/front_assets/images_other/spot/middle/s133-01.jpg',
      alt: 'Ramen',
      name: 'Onomichi Ramen',
      desc: ' Chicken Broth, Ramen Noodles, Soy sauce, Shashu pork, Togarashi, Fish cakes, Seafood, Corn, Bamboo shoots, Garlic, ajitsuke tamago (ramen egg), Bean sprouts, Mushrooms, Kimchi, Yuzukosho, Raw shredded cabbage ',
      price: '15.99',
      button: 'Order Now',
    },
    {
      img: 'https://upload.wikimedia.org/wikipedia/commons/8/88/Misen_Taiwan_Ramen_20180929.jpg',
      alt: 'Ramen',
      name: 'Nagoya Ramen',
      desc: ' Cabbage, Broth(a mix of Sesame oil, Ginger, Garlic, Scallion, Dashi powder, Mirin, Sake, Sea salt, and water), Ramen Noodles, Char siu, Kakuni, Ramen egg, Beans sprouts, Kikurage, Raw shredded cabbage, Kamaboko, Shichimi togarashi ',
      price: '16.99',
      button: 'Order Now',
    },
    {
      img: 'https://media-cdn.tripadvisor.com/media/photo-s/04/b4/78/82/caption.jpg',
      alt: 'Ramen',
      name: 'Hakodate Ramen',
      desc: ' Chicken broth, Chili Bean Sauce/Paste, Sesame Seeds and Sesame Oil, White pepper powder, Miso, Ramen Noodles, Corn, Bamboo shoots, Garlic, ajitsuke tamago (ramen egg),  Bean sprouts, Mushrooms, Raw shredded cabbage ',
      price: '14.99',
      button: 'Order Now',
    },
  ];
  
  export const dessertDataFull = [
    {
      img: 'https://images.japancentre.com/recipes/pics/1009/main/1009-yuzu-castella.jpg?1469573416',
      alt: 'Castella Cake',
      name: 'Castella Cake',
      desc: 'Treat yourself with this super moist Japanese sponge cake with a hint of sweetness from honey! It makes the perfect holiday or hostess gift too',
      price: '9.99',
      button: 'Order Now',
    },
    {
      img: 'https://1.bp.blogspot.com/-WmrqlZAnivs/VmDCJaciTpI/AAAAAAAACQc/Kf8uQQa0EkU/s1600/Anmitsu-Japanese-Summer-Desert.jpg',
      alt: 'Anmitsu',
      name: 'Anmitsu',
      desc: 'It’s a Japanese wagashi dessert with agar jelly, fruits, mochi, red bean paste, green tea ice cream and a good drizzle of sweet black sugar syrup',
      price: '10.99',
      button: 'Order Now',
    },
    {
      img: 'https://i.pinimg.com/originals/14/94/0a/14940ae9c6da4f841910a7f5478ba7fe.jpg',
      alt: 'Anpan',
      name: 'Anpan',
      desc: 'A classic Japanese pastry with sweet red bean paste inside a soft delicious bread. It has a hint of sweetness, wrapped in a soft, smooth and delicious bun',
      price: '11.99',
      button: 'Order Now',
    },
    {
      img: 'https://i.pinimg.com/originals/82/9e/b7/829eb7b15bc3d0b05d8f82f95e1a47b8.jpg',
      alt: 'Furutsu Sando',
      name: 'Furutsu Sando',
      desc: "Brighten your day with Japanese Fruit Sandwich, it's Juicy fresh fruits embedded in chilled whipped cream between two slices of Japanese milk bread",
      price: '12.99',
      button: 'Order Now',
    },
    {
      img: 'https://images.squarespace-cdn.com/content/v1/563858d6e4b08459c5ff1ccc/1467078294254-SWKY3M66KDNHCCX0F9H7/ke17ZwdGBToddI8pDm48kMJbebPoQWBOM63Hqc5eeghZw-zPPgdn4jUwVcJE1ZvWxYb2krSYGNt8NUBfJA7VeKmWLI2zvYWH8K3-s_4yszcp2ryTI0HqTOaaUohrI8PIcScCJQBLSQRVokrhBAY2JUY3vDqeWt1C7prX_D7EZU4KMshLAGzx4R3EDFOm1kBS/wagashi+sweets+kyoto?format=750w',
      alt: 'Wagashi ',
      name: 'Wagashi ',
      desc: 'Japanese sweets, are delightful tea treats eaten across Japan. It’s an art form that serves meaningful traditions of the Japanese culture.',
      price: '17.99',
      button: 'Order Now',
    },
    {
      img: 'https://cookwithkathy.files.wordpress.com/2016/06/st261.jpg?w=468',
      alt: 'Parfait',
      name: 'Parfait',
      desc: 'Delightful Japanese Fruit Parfait recipe made with delicious layers of sponge cakes, granolas, fresh whipped cream, and ice cream, topped with fresh fruits',
      price: '15.99',
      button: 'Order Now',
    },
  ];
  
  export const drinksDataFull = [
    {
      img: 'https://www.moshimoshi-nippon.jp/wp/wp-content/uploads/2019/08/4bb369177a6d00bee764f8a284d3cbb4.jpeg',
      alt: 'Cream Soda',
      name: 'Cream Soda',
      desc: 'Treat yourself with this One of a favorite childhood drinks from Japan is Cream Soda, a delicious melon flavored soda drink with a scoop of vanilla ice cream',
      price: '4.99',
      button: 'Order Now',
    },
    {
      img: 'https://chefjacooks.com/wp-content/uploads/2019/07/amazake-square.jpg',
      alt: 'Amazake',
      name: 'Amazake',
      desc: 'Creamy with a natural mild sweetness, Amazake or sweet sake is a popular Japanese hot drink during the New Year’s and Hina Matsuri(Doll Festival)',
      price: '6.99',
      button: 'Order Now',
    },
    {
      img: 'https://www.superhealthykids.com/wp-content/uploads/2010/12/May-Recipes-14.jpg',
      alt: 'Chocolate Banana',
      name: 'Chocolate Banana',
      desc: 'Power charge your day with Chocolate Banana Smoothie made with velvety soy milk blended with banana! Top with whipped cream/colorful sprinkles',
      price: '8.99',
      button: 'Order Now',
    },
    {
      img: 'https://www.savingdessert.com/wp-content/uploads/2011/11/Pumpkin-Pie-Smoothie-4.jpg',
      alt: 'Pumpkin Smooth',
      name: 'Pumpkin Smooth',
      desc: 'Sweet and flavorful pumpkin smoothie made with pumpkin puree, Greek yogurt, pumpkin pie spice, and almond milk. Toped with a bit cinnamon',
      price: '9.99',
      button: 'Order Now',
    },
    {
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRE_cwZk9bA58eMDMu8dqC04inUhaY-hHHYvA&usqp=CAU',
      alt: 'Matcha Green Tea Latte ',
      name: 'Matcha Green Tea ',
      desc: 'This is a creamy and frothy cup of Matcha Green Tea Latte. Enjoy this delicious drink at home by mixing bittersweet matcha green tea with warm milk',
      price: '10.99',
      button: 'Order Now',
    },
    {
      img: 'https://i.pinimg.com/originals/8f/2b/5a/8f2b5a6398ef8d4d04f69c14b366bbf4.jpg',
      alt: 'Iced Coffee',
      name: 'Iced Coffee',
      desc: 'The treat we look forward to the most in the morning is a cup of Japanese Iced Coffee. It releases all the wonderful flavors and aromatics from the coffee beans',
      price: '9.99',
      button: 'Order Now',
    },
  ];
  
  export const dataAll = [
    {
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQDfKkmf2J0C20_1dGr10gC2l20K8B8d64f_g&usqp=CAU',
      alt: 'Ramen',
      category: 'Ramen',
      name: 'Shoyu Ramen',
      desc: 'Chicken Broth, Ramen Noodles, Soy sauce, Shashu pork, Togarashi, Fish cakes, Seafood, Corn, Bamboo shoots, Garlic, ajitsuke tamago (ramen egg), Bean sprouts, Mushrooms, Kimchi, Yuzukosho, Raw shredded cabbage',
      price: '15.99',
      button: 'Order Now',
    },
    {
      img: 'https://gastroplant.com/wp-content/uploads/2019/08/1406_Vegan-Shio-Ramen_550.jpg',
      alt: 'Ramen',
      category: 'Ramen',
      name: 'Shio Ramen',
      desc: ' Cabbage, Broth(a mix of Sesame oil, Ginger, Garlic, Scallion, Dashi powder, Mirin, Sake, Sea salt, and water), Ramen Noodles, Char siu, Kakuni, Ramen egg, Beans sprouts, Kikurage, Raw shredded cabbage, Kamaboko, Shichimi togarashi',
      price: '17.99',
      button: 'Order Now',
    },
    {
      img: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/miso-ramen-514e2ca.jpg?quality=90&webp=true&resize=440,400',
      alt: 'Ramen',
      category: 'Ramen',
      name: 'Miso Ramen',
      desc: ' Chicken broth, Chili Bean Sauce/Paste, Sesame Seeds and Sesame Oil, White pepper powder, Miso, Ramen Noodles, Corn, Bamboo shoots, Garlic, ajitsuke tamago (ramen egg),  Bean sprouts, Mushrooms, Raw shredded cabbage ',
      price: '19.99',
      button: 'Order Now',
    },
    {
      img: 'https://cloudfront.chushikokuandtokyo.org/front_assets/images_other/spot/middle/s133-01.jpg',
      alt: 'Ramen',
      category: 'Ramen',
      name: 'Onomichi Ramen',
      desc: ' Chicken Broth, Ramen Noodles, Soy sauce, Shashu pork, Togarashi, Fish cakes, Seafood, Corn, Bamboo shoots, Garlic, ajitsuke tamago (ramen egg), Bean sprouts, Mushrooms, Kimchi, Yuzukosho, Raw shredded cabbage ',
      price: '15.99',
      button: 'Order Now',
    },
    {
      img: 'https://upload.wikimedia.org/wikipedia/commons/8/88/Misen_Taiwan_Ramen_20180929.jpg',
      alt: 'Ramen',
      category: 'Ramen',
      name: 'Nagoya Ramen',
      desc: ' Cabbage, Broth(a mix of Sesame oil, Ginger, Garlic, Scallion, Dashi powder, Mirin, Sake, Sea salt, and water), Ramen Noodles, Char siu, Kakuni, Ramen egg, Beans sprouts, Kikurage, Raw shredded cabbage, Kamaboko, Shichimi togarashi ',
      price: '16.99',
      button: 'Order Now',
    },
    {
      img: 'https://media-cdn.tripadvisor.com/media/photo-s/04/b4/78/82/caption.jpg',
      alt: 'Ramen',
      category: 'Ramen',
      name: 'Hakodate Ramen',
      desc: ' Chicken broth, Chili Bean Sauce/Paste, Sesame Seeds and Sesame Oil, White pepper powder, Miso, Ramen Noodles, Corn, Bamboo shoots, Garlic, ajitsuke tamago (ramen egg),  Bean sprouts, Mushrooms, Raw shredded cabbage ',
      price: '14.99',
      button: 'Order Now',
    },
    {
      img: 'https://images.japancentre.com/recipes/pics/1009/main/1009-yuzu-castella.jpg?1469573416',
      alt: 'Castella Cake',
      category: 'Dessert',
      name: 'Castella Cake',
      desc: 'Treat yourself with this super moist Japanese sponge cake with a hint of sweetness from honey! It makes the perfect holiday or hostess gift too',
      price: '9.99',
      button: 'Order Now',
    },
    {
      img: 'https://1.bp.blogspot.com/-WmrqlZAnivs/VmDCJaciTpI/AAAAAAAACQc/Kf8uQQa0EkU/s1600/Anmitsu-Japanese-Summer-Desert.jpg',
      alt: 'Anmitsu',
      category: 'Dessert',
      name: 'Anmitsu',
      desc: 'It’s a Japanese wagashi dessert with agar jelly, fruits, mochi, red bean paste, green tea ice cream and a good drizzle of sweet black sugar syrup',
      price: '10.99',
      button: 'Order Now',
    },
    {
      img: 'https://i.pinimg.com/originals/14/94/0a/14940ae9c6da4f841910a7f5478ba7fe.jpg',
      alt: 'Anpan',
      category: 'Dessert',
      name: 'Anpan',
      desc: 'A classic Japanese pastry with sweet red bean paste inside a soft delicious bread. It has a hint of sweetness, wrapped in a soft, smooth and delicious bun',
      price: '11.99',
      button: 'Order Now',
    },
    {
      img: 'https://i.pinimg.com/originals/82/9e/b7/829eb7b15bc3d0b05d8f82f95e1a47b8.jpg',
      alt: 'Furutsu Sando',
      category: 'Dessert',
      name: 'Furutsu Sando',
      desc: "Brighten your day with Japanese Fruit Sandwich, it's Juicy fresh fruits embedded in chilled whipped cream between two slices of Japanese milk bread",
      price: '12.99',
      button: 'Order Now',
    },
    {
      img: 'https://images.squarespace-cdn.com/content/v1/563858d6e4b08459c5ff1ccc/1467078294254-SWKY3M66KDNHCCX0F9H7/ke17ZwdGBToddI8pDm48kMJbebPoQWBOM63Hqc5eeghZw-zPPgdn4jUwVcJE1ZvWxYb2krSYGNt8NUBfJA7VeKmWLI2zvYWH8K3-s_4yszcp2ryTI0HqTOaaUohrI8PIcScCJQBLSQRVokrhBAY2JUY3vDqeWt1C7prX_D7EZU4KMshLAGzx4R3EDFOm1kBS/wagashi+sweets+kyoto?format=750w',
      alt: 'Wagashi ',
      category: 'Dessert',
      name: 'Wagashi ',
      desc: 'Japanese sweets, are delightful tea treats eaten across Japan. It’s an art form that serves meaningful traditions of the Japanese culture.',
      price: '17.99',
      button: 'Order Now',
    },
    {
      img: 'https://cookwithkathy.files.wordpress.com/2016/06/st261.jpg?w=468',
      alt: 'Parfait',
      category: 'Dessert',
      name: 'Parfait',
      desc: 'Delightful Japanese Fruit Parfait recipe made with delicious layers of sponge cakes, granolas, fresh whipped cream, and ice cream, topped with fresh fruits',
      price: '15.99',
      button: 'Order Now',
    },
    {
      img: 'https://www.moshimoshi-nippon.jp/wp/wp-content/uploads/2019/08/4bb369177a6d00bee764f8a284d3cbb4.jpeg',
      alt: 'Cream Soda',
      category: 'Drink',
      name: 'Cream Soda',
      desc: 'Treat yourself with this One of a favorite childhood drinks from Japan is Cream Soda, a delicious melon flavored soda drink with a scoop of vanilla ice cream',
      price: '4.99',
      button: 'Order Now',
    },
    {
      img: 'https://chefjacooks.com/wp-content/uploads/2019/07/amazake-square.jpg',
      alt: 'Amazake',
      category: 'Drink',
      name: 'Amazake',
      desc: 'Creamy with a natural mild sweetness, Amazake or sweet sake is a popular Japanese hot drink during the New Year’s and Hina Matsuri(Doll Festival)',
      price: '6.99',
      button: 'Order Now',
    },
    {
      img: 'https://www.superhealthykids.com/wp-content/uploads/2010/12/May-Recipes-14.jpg',
      alt: 'Chocolate Banana',
      category: 'Drink',
      name: 'Chocolate Banana',
      desc: 'Power charge your day with Chocolate Banana Smoothie made with velvety soy milk blended with banana! Top with whipped cream/colorful sprinkles',
      price: '8.99',
      button: 'Order Now',
    },
    {
      img: 'https://www.savingdessert.com/wp-content/uploads/2011/11/Pumpkin-Pie-Smoothie-4.jpg',
      alt: 'Pumpkin Smooth',
      category: 'Drink',
      name: 'Pumpkin Smooth',
      desc: 'Sweet and flavorful pumpkin smoothie made with pumpkin puree, Greek yogurt, pumpkin pie spice, and almond milk. Toped with a bit cinnamon',
      price: '9.99',
      button: 'Order Now',
    },
    {
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRE_cwZk9bA58eMDMu8dqC04inUhaY-hHHYvA&usqp=CAU',
      alt: 'Matcha Green Tea Latte ',
      category: 'Drink',
      name: 'Matcha Green Tea ',
      desc: 'This is a creamy and frothy cup of Matcha Green Tea Latte. Enjoy this delicious drink at home by mixing bittersweet matcha green tea with warm milk',
      price: '10.99',
      button: 'Order Now',
    },
    {
      img: 'https://i.pinimg.com/originals/8f/2b/5a/8f2b5a6398ef8d4d04f69c14b366bbf4.jpg',
      alt: 'Iced Coffee',
      category: 'Drink',
      name: 'Iced Coffee',
      desc: 'The treat we look forward to the most in the morning is a cup of Japanese Iced Coffee. It releases all the wonderful flavors and aromatics from the coffee beans',
      price: '9.99',
      button: 'Order Now',
    },
  ];
  